### ISSUE TITLE
Fill out bus statistics

### ISSUE THREAD

**Issue by frizensami** [frizensami/cs4223-as2#20]
1. Amount of Data traffic in bytes on the bus (this is due to bus read, bus read exclusive, bus writeback, and bus update transactions). Only include the traffic for data and not for address. Thus invalidation requests do not contribute to the data traffic.

2. Number of invalidations or updates on the bus

3. Distribution of accesses to private data versus shared data (for example, access to modified state is private, while access to shared state is shared data)

**Comment by AlvianPrasetya** [comment]
@frizensami Don't think number of private access/public access could be counted from bus side, since a read hit will most likely not acquire the bus (read hit in MESI for example doesn't have anything to do with the bus).

**Comment by AlvianPrasetya** [comment]
(1) and (2) done on PR #27

**Comment by AlvianPrasetya** [comment]
Private/public accesses count is maintained by the Cache in a CacheStatistics datatype.
