### ISSUE TITLE
Running blackscholes with Dragon causes unknown state error

### ISSUE THREAD

**Issue by frizensami** [frizensami/cs4223-as2#30]
cs4223-as2-exe: Unknown block state in Dragon Protocol **(i debugged this to be the Nothing state)**
CallStack (from HasCallStack):
  error, called at src/DragonProtocol.hs:330:24 in cs4223-as2-0.1.0.0-2VFgl0DBtRyl7oZg7Hn2u:DragonProtocol

**Comment by frizensami** [comment]
Previous traces:

Processor #3,  Protocol State: Just (DragonProtocol DragonWaitMemoryRead): StoreInstruction 2145208448
Processor #0,  Protocol State: Nothing: OtherInstruction 3
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitCacheWrite): StoreInstruction 2115649696
Processor #3,  Protocol State: Just (DragonProtocol DragonWaitMemoryRead): StoreInstruction 2145208448
Processor #0,  Protocol State: Nothing: LoadInstruction 8969796
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitCacheWrite): StoreInstruction 2115649696
Processor #3,  Protocol State: Just (DragonProtocol DragonWaitMemoryRead): StoreInstruction 2145208448
Processor #0,  Protocol State: Just (DragonProtocol DragonWaitCacheRead): LoadInstruction 8969796
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitCacheWrite): StoreInstruction 2115649696
Processor #3,  Protocol State: Just (DragonProtocol DragonWaitCacheRewrite): StoreInstruction 2145208448
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitCacheWrite): StoreInstruction 2115649696
Processor #3,  Protocol State: Nothing: OtherInstruction 2
Processor #3,  Protocol State: Nothing: OtherInstruction 2
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitBusTr): StoreInstruction 2115649696
Processor #3,  Protocol State: Nothing: OtherInstruction 2
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitBusTr): StoreInstruction 2115649696
Processor #3,  Protocol State: Nothing: StoreInstruction 2145208456
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitBusTr): StoreInstruction 2115649696
Processor #3,  Protocol State: Just (DragonProtocol DragonWaitCacheWrite): StoreInstruction 2145208456
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitBusTr): StoreInstruction 2115649696
Processor #3,  Protocol State: Nothing: OtherInstruction 2
Processor #3,  Protocol State: Nothing: OtherInstruction 2
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitBusTr): StoreInstruction 2115649696
Processor #3,  Protocol State: Nothing: OtherInstruction 2
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitBusTr): StoreInstruction 2115649696
Processor #3,  Protocol State: Nothing: StoreInstruction 2145208496
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitBusTr): StoreInstruction 2115649696
Processor #3,  Protocol State: Just (DragonProtocol DragonWaitCacheWrite): StoreInstruction 2145208496
Processor #0,  Protocol State: Nothing: OtherInstruction 14
Processor #1,  Protocol State: Nothing: OtherInstruction 23216
Processor #2,  Protocol State: Just (DragonProtocol DragonWaitBusTr): StoreInstruction 2115649696
cs4223-as2-exe: Unknown block state in Dragon Protocol = Nothing

**Comment by AlvianPrasetya** [comment]
Fixed #31
