### ISSUE TITLE
Implement Bus Contract

### ISSUE THREAD

**Issue by frizensami** [frizensami/cs4223-as2#7]
1. Bus must be reconstructed with updated list of **caches** on every call of `runAllSimulationCycles` while maintaining its current state, including its own private `Memory` unit. This is to ensure that the Bus has the most up-to-date view of all the caches .
2. Implement `Bus.acquire` and `Bus.release` methods for a processor to lockdown the bus. `Bus.isFree` must report True if the bus is released.
3. Implement `Bus.isBusy` which indicates that the Bus is completing a memory operation and cannot be used.
4. Implement pattern matching for `MESIBusRd`, `MESIBusRdX`, `DragonBusRd`, `DragonUpdate` protocol events.

**Comment by frizensami** [comment]
Points 1 - 3 are done in 40f4a4e - heads up to @AlvianPrasetya

**Comment by AlvianPrasetya** [comment]
Affirmative @frizensami , working on bus transactions...

**Comment by frizensami** [comment]
:+1: am adding tests for the `OtherInstructions` part now to make sure we don't regress on that when we add the Protocol components

**Comment by frizensami** [comment]
Travis CI added in https://github.com/frizensami/cs4223-as2/commit/2ca8e1d6ac9b7785865168e842f8771ef0bab90a

**Comment by frizensami** [comment]
Changed to different implementation
